#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Stephane Bocquet <stephane_bocquet@hotmail.com>
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c) 2011 Stephane Bocquet
# @copyright Copyright (c) 2012 Marcel Beck
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

# Enable/disable service
if [ "$(omv_config_get "//services/couchpotato/enable")" != "1" ]; then
	echo "# Stop/Disable Couchpotato"
	invoke-rc.d couchpotato stop 1>/dev/null 2>&1 || true
	update-rc.d couchpotato disable 2>&1
	exit 0
fi

#why stop if enabled?
#echo "# Stop Couchpotato"
#invoke-rc.d couchpotato stop 1>/dev/null 2>&1 || true

echo "# Start/Enable Couchpotato"
update-rc.d couchpotato enable 2>&1
service couchpotato start 2>&1
