#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
    if [ -z "$2" ]; then
        echo "Updating init script links and actions"
        invoke-rc.d --force couchpotato stop &>/dev/null
        update-rc.d couchpotato disable &>/dev/null
    fi


    if ! grep -q "^couchpotato:" /etc/passwd; then
        echo "Adding couchpotato user..."
        useradd --create-home --groups users --no-user-group --shell /usr/sbin/nologin couchpotato
    else
        echo "couchpotato user already exists."
    fi

    if [ -e /var/run/couchpotato ]; then
        echo "Cleaning old pid file..."
        rm /var/run/couchpotato -Rf
    fi


    if [ ! -f /home/couchpotato/.couchpotato/settings.conf ]; then
        echo "[core]
show_wizard = 1
[updater]
git_command = git" > /home/couchpotato/.couchpotato/settings.conf
        chown couchpotato:users /home/couchpotato/.couchpotato/settings.conf
    fi


    chown -R couchpotato:users /opt/couchpotato
    
    #update-rc.d couchpotato defaults

    ;;
abort-upgrade|abort-remove|abort-deconfigure)
    ;;
*)
    echo "postinst called with unknown argument" >&2
    exit 1
    ;;
esac

exit 0
