#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions
echo "postinst called with $1 - $2"
case "$1" in
	configure)
    #if [ -z "$2" ]; then
    #    echo "Updating init script links and actions"
    #    invoke-rc.d --force couchpotato stop &>/dev/null
    #    update-rc.d couchpotato disable &>/dev/null
    #fi

    if ! grep -q "^couchpotato:" /etc/passwd; then
        echo "Adding couchpotato user..."
        useradd --create-home --groups users --no-user-group --shell /usr/sbin/nologin couchpotato
    else
        echo "couchpotato user already exists."
    fi

    if [ -e /var/run/couchpotato ]; then
        echo "Cleaning old pid file..."
        rm /var/run/couchpotato -Rf
    fi

    if [ -e /opt/couchpotato/git ]; then
        mv /opt/couchpotato/git /opt/couchpotato/.git
    fi

    if [ ! -f /home/couchpotato/.couchpotato/settings.conf ]; then
		mkdir /home/couchpotato/.couchpotato
		chown couchpotato:users /home/couchpotato/.couchpotato -R
        echo "[core]
show_wizard = 1
[updater]
git_command = git" > /home/couchpotato/.couchpotato/settings.conf
        chown couchpotato:users /home/couchpotato/.couchpotato/settings.conf
    fi


    chown -R couchpotato:users /opt/couchpotato
    
    update-rc.d couchpotato defaults
	
    if ! omv_config_exists "/config/services/couchpotato"; then
        echo "Initial configuration."
        object="<enable>0</enable>"
        object="${object}<showtab>0</showtab>"
        omv_config_add_element "/config/services" "couchpotato" "${object}" true
    fi

    ;;
abort-upgrade|abort-remove|abort-deconfigure)
    ;;
*)
    echo "postinst called with unknown argument" >&2
    exit 1
    ;;
esac

exit 0
